server:
  port: 8085
  
spring:  data:    mongodb:      uri: mongodb+srv://sai:saikumar1@cluster0.bbg3l.mongodb.net/AdminService?retryWrites=true&w=majority  application:    name: admin-service
      
eureka:  instance:    hostname: localhost
springdoc:  swagger-ui:    path: /swagger-ui.html     
jwt:
  secret: key420